### PR TITLE
Add favorites feature

### PR DESCRIPTION
**Pull request by hb20007**
The favorites are stored as map names in `Map Files/.favorites`. This is how it looks like:

image

### CODE REVIEW

**Comment by NoxPhoenix** [comment]
I love this feature and this all looks good.
There is only one thing I would like to address and I am open to helping contribute to the solution as well.

The current styling of the heart can be difficult to see over certain map images.
We could either change the heart style or reformat the cards to have them elsewhere on the card.
Thoughts @hb20007 ?

**Comment by hb20007** [comment]
I have a few suggestions in terms of changing the heart style. I will use these "before" pictures for comparison:

image

image

### 1. Using the brighter `red` instead of `crimson` color:

image

image

### 2. Adding a black shadow (`text-shadow: 0 0 5px #000`):

image

image

### 3. Adding a red glow effect (`text-shadow: 0px 0px 5px crimson`):

image

image

I also tried playing around with adding a background behind the icon, but I didn't really like the result:

```css
.heart-container {
    position: absolute;
    top: 5px;
    background: #aaaa;
    padding: 2px 5px 1px 5px;
    border-radius: 5px;
    right: 5px;
    color: red;
    z-index: 99;
}
.fa-heart {
    text-shadow: 0 0 5px #000
}
```

image

**Comment by NoxPhoenix** [comment]
I noticed that you use the bright red as a hover, what would you do for the hover if you changed to using the bright red with a shadow?

**Comment by NoxPhoenix** [comment]
The two maps I saw it worst on are maps with similar colors or just an overall lot of information in that corner.
heartdb
hearttext

**Comment by hb20007** [comment]
I think the best solution so far with these 2 maps in mind is a combination of `color: red` and `text-shadow: 0 0 5px #000`.

This is how it would look like.

Before:

image

After:

image

It's not perfect but there's definitely an improvement.

As for the hover effect, if we are to go with this solution, then we can use `color: orangered` and perhaps add an animation to make it more visible.

**Comment by LiquidLemon** [comment]
Don't you think there might always be a chance that some future thumbnail will blend with the icon? There's a lot of free space on the "Load" button, I think it could work well if you made it smaller instead and put a favorite button on the right of it. This way the UI is also simpler with all the buttons grouped together. I could make a mock later if I haven't explained it well.

**Comment by hb20007** [comment]
@LiquidLemon, yes a mock would be helpful.

**Comment by LiquidLemon** [comment]
Something like this:

Mock

**Comment by hb20007** [comment]
@LiquidLemon It's an interesting suggestion. When I get time, I will implement it in CSS and post a screenshot here to evaluate how it looks.

**Comment by hb20007** [comment]
@LiquidLemon  I tried implementing this in CSS:

image

I'm not a huge fan to be honest. I feel like the Load button is more important and I prefer the previous design where it was bigger and centered. On the other hand, it does solve the problem we had.

@NoxPhoenix What do you think about this design?

**Comment by hb20007** [comment]
That also gave me another idea.

@NoxPhoenix @LiquidLemon , what do you guys think of this?

image

**Comment by LiquidLemon** [comment]
I'm not crazy about it but it does solve the issue. I don't really feel like the load button being smaller is an issue as it's still easily accessible but it's not my call to make.

**Comment by NoxPhoenix** [comment]
I like it next to the load button the best, what does it look like if the padding on all buttons was a little smaller?

**Comment by hb20007** [comment]
@NoxPhoenix I will try different things along those lines and will update the PR when I get time

**Comment by hb20007** [comment]
@NoxPhoenix , @LiquidLemon, I updated the PR. I think a margin of `7px` instead of `10px` looks best. This is how it looks like now:

image

**Comment by m-henderson** [comment]
@NoxPhoenix hey, did we still want this feature added? I have free time to work on it.

**Comment by NoxPhoenix** [comment]
I am looking at this, this week.

**Pull request closed without merging**
